services:
  rtorrent:
    build:
      context: .
      tags:
        - ghcr.io/arnoldthebat/rtorrent:latest
        - ghcr.io/arnoldthebat/rtorrent:0.4
    image: ghcr.io/arnoldthebat/rtorrent:latest
    container_name: rtorrent
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - $HOME/dev/cobbling/rtorrent:/data/rtorrent
    ports:
      - "55555:55555"
      - "55555:55555/udp"
      - "8000:8000"
    restart: unless-stopped